Add error

diff --git a/.github/workflows/pr-master.yml b/.github/workflows/pr-master.yml
--- a/.github/workflows/pr-master.yml
+++ b/.github/workflows/pr-master.yml
@@ -43,7 +43,7 @@ jobs:
 
         if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
           echo "Deployment validation failed. Extracting error messages..."
-          cat deploy_output.log | grep -A 10 -E "(ERROR|Failed)" || echo "No specific error message found."
+          cat deploy_output.log | grep -A 10 -E "(ERROR|Failed|INVALID|Unhandled)" || echo "No specific error message found."
           exit $DEPLOY_EXIT_CODE
         else
           echo "Deployment validation succeeded."
